### ISSUE TITLE
problemi conversione file multipli

### ISSUE THREAD

**Issue by yakky** [italia/docs-italia-convertitore-web#11]
conversione multipla e caricamento multiplo - il drag and drop di più files funziona ma la selezione multipla attraverso finestra di caricamento no (nella finestra di dialogo non posso effettuare la multiselezione con ctrl o shift)

**Comment by francescozaia** [comment]
Mi sa che fa parte delle opzioni della libreria JS che abbiamo usato, DropzoneJS, in particolare `maxFiles` e `uploadMultiple` forse (da [qui](http://www.dropzonejs.com/#config-uploadMultiple))?

**Comment by yakky** [comment]
Sì, va gestito però la conversione splittando un po' di logica
In questo caso cosa facciamo, partono N email (una per ogni file) o accorpiamo tutto in un'unica?
