### ISSUE TITLE
Update dei comandi di conversione a 0.4

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-convertitore-web#19]
Ho pubblicato la [release 0.4](https://github.com/italia/docs-italia-comandi-conversione/releases/tag/v0.4) che contiene la soluzione per questo errore https://github.com/italia/docs-italia-comandi-conversione/issues/42. @francescozaia ha cercato di convertire un ODT oggi, il che dovrebbe aver scatenato questo errore quindi forse ti ritroverai una mail da Sentry in proposito

**Comment by yakky** [comment]
@danse nonostante il deploy della 0.4 continuo a ricevere l'errore 
```
couldn't parse docx file
```
il comando eseguito è `converti file.odt`
