### ISSUE TITLE
Altri formati nell'header

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-convertitore-web#27]
L'header dice che il convertitore supporta `.docx` ed `.odt` ma in realtà supportiamo altri formati fra cui HTML e Markdown. Credo che per lo meno `.md` possa essere citato, visto che parecchi utenti potrebbero essere familiari col formato. Nota che le immagini non verranno convertite correttamente perché sono codificate in files esterni, però può essere comodo convertire lunghi testi che vengano da un README per esempio, può succedere nel caso di doc tecnica. Se poi ci sarà richiesta potremo aggiungere facilmente il supporto per i files esterni.

Potremmo valutare se citare altri formati tipo LaTeX (comune in uso accademico) o MediaWiki (utile se si importa doc da un wiki). Sono tutti già supportati

**Comment by yakky** [comment]
Questa direi che è collegata al miglioramento UX generale con aggiornamento dei vari copy

**Comment by danse** [comment]
gli altri formati sono ora citati in https://docs-italia-staging.teamdigitale.it/converti/
