### ISSUE TITLE
L'opzione "livello singolo" non funziona

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-convertitore-web#33]
@pablopers ci segnala che l'opzione non funziona per lui. @pablopers puoi allegare il documento?

**Comment by pablopers** [comment]
[DocDig.docx](https://github.com/italia/docs-italia-convertitore-web/files/2309957/DocDig.docx)
grazie

**Comment by danse** [comment]
in questo documento, _documentazione digitale_ è formattato come header di primo livello, e quindi è usato da `converti` per produrre un capitolo. Settando lo stile di _documentazione digitale_ come titolo, ottengo un solo file nel risultato, indipendentemente dall'opzione _livello singolo_
