### ISSUE TITLE
Le mail con il risultato della conversione hanno il mittente impostato su info@example.org

### ISSUE THREAD

**Issue by pdavide** [italia/docs-italia-convertitore-web#39]

**Comment by francescozaia** [comment]
Curioso che, nonostante il [fix sia nella codebase](https://github.com/italia/docs-italia-convertitore-web/commit/82589eeaa79289b96e6be124512c2a9a816cd112) e che sia già stato deployato più volte il codice attraverso gli script ansible, questa issue non sia ancora sistemata.

**Comment by yakky** [comment]
@francescozaia @pdavide questa segnalazione è ancora valida?

**Comment by pdavide** [comment]
Si potrebbe fare un check dopo la risoluzione della #40 che di fatto impedisce di usare il convertitore.

**Comment by yakky** [comment]
Ok tks, allora guardiamo la #40 intanto

**Comment by callmesangio** [comment]
@pdavide Ciao, attualmente le mail del convertitore mi arrivano con mittente impostato a `no-reply@docs.italia.it`.
Potresti cortesemente fare anche tu una verifica? Grazie

**Comment by pdavide** [comment]
Confermo `no-reply@docs.italia.it`.

**Comment by callmesangio** [comment]
Ottimo, grazie mille 👍
