### ISSUE TITLE
Il caricamento dei documenti nel convertitore web fallisce

### ISSUE THREAD

**Issue by pdavide** [italia/docs-italia-convertitore-web#40]
Dopo il drop del file nello spazio di caricamento, oppure dopo la scelta da file browser, il caricamento non va a buon fine.

**Comment by callmesangio** [comment]
@pdavide Ciao, hai modo di fornirmi un documento per il quale il caricamento fallisce? Al momento non riesco a riprodurre il problema.

Questa issue sembra essere un duplicato di https://github.com/italia/docs.italia.it/issues/264

**Comment by pdavide** [comment]
Ciao @sanjioh ho fatto una prova e adesso il caricamento e la conversione funzionano correttamente. Resta solo una stringa "undefined" nell'icona del file dopo il trascinamento nella drop zone, ma non impatta sul funzionamento complessivo.

**Comment by callmesangio** [comment]
@pdavide Grazie mille, apro una issue sulla stringa sbagliata nell'icona e chiudo questa.
