### ISSUE TITLE
Aggiornamento alla versione attuale di Bootstrap Italia 1.3

### ISSUE THREAD

**Issue by SimoneNephila** [italia/docs-italia-convertitore-web#44]
Aggiornare tutta la piattaforma a Bootstrap Italia 1.3.x, in modo da avere le più recenti feature e componenti.

**Comment by yakky** [comment]
Le classi esistenti sono già compatibili e dal momento che gli asset relativi sono già forniti da docs italia non abbiamo bisogno di ulteriori interventi
