### ISSUE TITLE
Uso del comando di conversione dedicato

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-convertitore-web#7]
Attualmente il servizio converte documenti applicando la [seguente logica](https://github.com/italia/docs-italia-convertitore-web/blob/master/docs_italia_convertitore_web/tasks.py#L82):

- i files con estensione `.docx` vengono convertiti usando `converti`
- gli altri files vengono convertiti usando pandoc, senza opzioni

Questa logica non produce i migliori risultati. Al fine di migliorare questo aspetto ho pensato di [aggiungere un comando dedicato al servizio](https://github.com/italia/docs-italia-comandi-conversione/issues/36), dopo di che questo servizio può fare riferimento direttamente a quel comando

**Comment by yakky** [comment]
Per il momento usiamo sempre `converti`
